version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: tomonorimatsumura/ubuntu18-ansible:stable
    steps:
      - checkout
      - run: AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN ansible-playbook ./.ansible/deploy.yml

workflows:
  build:
    jobs:
      - deploy
