version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0b:75:89:54:9a:2f:27:74:96:71:3f:bb:ab:67:3e:62"
      - run: python -m pip install --user boto ansible
      - run:
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
          command: ansible-playbook ./.ansible/deploy.yml

workflows:
  build:
    jobs:
      - deploy
